### ISSUE TITLE
setup issue due to FB rejecting user token

### ISSUE THREAD

**Issue by 34code** [ldziedziul/matterbook#5]
FB seems to be requiring app tokens now but the application is designed around user tokens ATM.

Any way to make it work with an app token?

The error I'm receiving on first run is:
`facebook.GraphAPIError: The access token does not belong to application {AppID}`

**Comment by ldziedziul** [comment]
Hi @34code, sorry for the late response. I think that your problem has a different cause than user tokens. But thanks to your notice about app tokens I've checked it and it turned out that we can use `app_id` and `app_secret` only for authentication and simplify the config file and make it read-only. Feel free to checkout new [v1.1](https://github.com/ldziedziul/matterbook/releases/tag/v1.1) release.

**Comment by 34code** [comment]
Thanks! Will checkout :)
